# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'npm ci'

- script: |
    npm run build
  displayName: 'npm run build'

- script: |
    cp -r .next/static .next/standalone/.next
    cp -r ./public .next/standalone/
  displayName: 'tracing files'

- script: |
    zip -r standalone.zip ./
    mv ./standalone.zip $(Build.ArtifactStagingDirectory)
  displayName: 'move directory'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish artifact'
